trigger: none
pr: none
resources:
  pipelines:
    - pipeline: Artifacts
      source: "Web CI (self-hosted)"
      trigger:
        branches:
          include: [main, development]
pool:
  name: rai-self-hosted
jobs:
  - job: DockerCICD
    steps:
      - checkout: none
      - script: |
          echo "Cleaning up..."
          rm -rf *
          rm -rf .[!.]*
          rm -rf $(Pipeline.Workspace)/Artifacts
          rm -rf $(Pipeline.Workspace)/release
        displayName: Clean up
      - download: Artifacts
        artifact: pack
      - bash: |
          APP_VERSION=$(ls $(System.Workspace)/Artifacts/pack | grep .zip | sed -E "s|.+-v||" | sed -E "s|.zip||")
          echo "##vso[task.setvariable variable=appVersion;]$APP_VERSION"
        displayName: appVersion
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: "$(Pipeline.Workspace)/Artifacts/pack/web-*.zip"
          destinationFolder: "$(Pipeline.Workspace)/out"
          cleanDestinationFolder: true
        displayName: "Extract ZIP Artifact"
      - script: swa deploy $(Pipeline.Workspace)/out --app-name stapp-fluent2-web --env production
        displayName: "Deploy Static Web App"
